#!/bin/zsh
COMMIT_MESSAGE=$1
if [ -z "$COMMIT_MESSAGE" ]; then echo "Error: Missing commit message"; exit 0; fi

BASE_DIR=$PWD
cd ../qualitymad.github.io
git add . && git commit -m "$COMMIT_MESSAGE" && git push
cd $BASE_DIR

