name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          # Navigate to your application directory
          cd ${{ secrets.VPS_APP_PATH || '/var/www/qualitymad.github.io' }}
          
          # Backup current version (optional)
          if [ -f "index.html" ]; then
            sudo cp -r . backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Create temporary directory for new files
          sudo mkdir -p /tmp/app-deploy
        
    - name: Copy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        source: "*"
        target: "/tmp/app-deploy/"

    - name: Finalize deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          # Navigate to application directory
          cd ${{ secrets.VPS_APP_PATH || '/var/www/qualitymad.github.io' }}
          
          # Remove old files (keep backups)
          sudo find . -maxdepth 1 -type f -not -name 'backup.*' -delete
          sudo find . -maxdepth 1 -type d -not -name '.' -not -name '..' -not -name 'backup.*' -exec rm -rf {} +
          
          # Move new files to final destination
          sudo mv /tmp/app-deploy/* .
          
          # Set proper permissions
          sudo chown -R www-data:www-data .
          sudo chmod -R 755 .
          sudo chmod 644 index.html
          
          # Clean up
          sudo rm -rf /tmp/app-deploy
          
          echo "Deployment completed successfully!"

    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi